### ISSUE TITLE
Error starting file onionservice.yaml

### ISSUE THREAD

**Issue by djuwa4** [kragniz/tor-controller#8]
Hello! I use centos7, kubectl version:
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

I am doing a deployment with a fixed address, the points:
Create echoserver.yaml:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - name: http-app
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - containerPort: 8080
kubectl apply -f echoserver.yaml
Then
openssl genrsa -out private_key 1024
kubectl create secret generic example-onion-key --from-file=private_key
And
Create an onion service, onionservice.yaml:
apiVersion: tor.k8s.io/v1alpha1
kind: OnionService
metadata:
  name: example-onion-service
spec:
  version: 2
  selector:
    app: http-app
  ports:
    - targetPort: 8080
      publicPort: 80
  privateKeySecret:
    name: example-onion-key
    key: private_key

After executing the command: kubectl apply -f onionservice.yaml 
I get an error:  error: unable to recognize "./onionservice.yaml": no matches for kind "OnionService" in version "tor.k8s.io/v1alpha1"

Please tell me how can I fix this?

**Comment by kragniz** [comment]
sounds like you haven't installed the custom resource.

What's the output of `kubectl get crd`?

**Comment by djuwa4** [comment]
> What's the output of `kubectl get crd`?
Oh sorry! I did not pay attention to the error when installing the tor-controller and was sure that it was installed. Now I corrected the error, installed the tor-controller, launched onionservice.yaml again. Now everything started perfectly. Thanks!
